export const WORKER_CONFIG = {
    COOL_DOWN_DURATION:300,
    BATCH_SIZE: 500,
    WEBHOOK_URL: Bun.env.WEBHOOK_URL || '',
    DEFAULT_WINDOW_MS: 10000,
    DEFAULT_THRESHOLD: 5,
    MAX_INGEST_BATCH:5000
};